export * from "./SplashScreen"

export * from "./CourseworkScreen"
export * from "./SubmissionScreen"
export * from "./LectureScreen"
export * from "./AssigmentScreen"
export * from "./StudentGradingScreen"
export * from "./GradingSelectScreen"
export * from "./TeacherTimetableScreen"

// export * from "./TeacherScreen/CourseScreen"
// export * from "./TeacherScreen/TimetableScreen"
export * from "./LoginScreen"
export * from "./HomeScreen"
export * from "./NewsDetailScreen"
export * from "./AddNewsScreen"
export * from "./AddBannersScreen"
export * from "./BannersListScreen"
export * from "./NewsListScreen"
export * from "./ForgotPasswordScreen"
export * from "./AdminMenu"
export * from "./StuCourseworkScreen"
export * from "./StuEditProfileScreen"
export * from "./StuProfileScreen"
export * from "./StuSubmissionDoneScreen"
export * from "./StuSubmissionScreen"
export * from "./StudentGradingScreen"
export * from "./TCScreen"
export * from "./AdminStudentList"
export * from "./AdminStudentListEdit"
export * from "./AdminLecturerList"
export * from "./AdminLecturerListEdit"
export * from "./AdminCourseLIst"
export * from "./AdminCourseListEdit"
